### ISSUE TITLE
Unable to convert excel file having empty sheets

### ISSUE THREAD

**Issue by sb4singh** [DaSpawn/xlsx-stream-reader#11]
TypeError: Cannot set property 'values' of undefined
    at XlsxStreamReaderWorkSheet._handleWorkSheetNode (/home/jarvis/Desktop/Projects/git/payroll/node_modules/xlsx-stream-reader/lib/worksheet.js:193:27)
    at SAXStream.<anonymous> (/home/jarvis/Desktop/Projects/git/payroll/node_modules/xlsx-stream-reader/lib/workbook.js:255:17)
    at emitOne (events.js:115:13)
    at SAXStream.emit (events.js:210:7)
    at SAXParser.me._parser.(anonymous function) [as onclosetag] (/home/jarvis/Desktop/Projects/git/payroll/node_modules/sax/lib/sax.js:258:17)
    at emit (/home/jarvis/Desktop/Projects/git/payroll/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/jarvis/Desktop/Projects/git/payroll/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/jarvis/Desktop/Projects/git/payroll/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/jarvis/Desktop/Projects/git/payroll/node_modules/sax/lib/sax.js:1293:13)
    at SAXStream.write (/home/jarvis/Desktop/Projects/git/payroll/node_modules/sax/lib/sax.js:239:18)

**Comment by hao10** [comment]
I have also encountered this problem
but just on windows 7
windows xp, windows 10 and macos is correct

**Comment by DaSpawn** [comment]
This may have been an old issue now resolved, please retry with latest master branch
