### ISSUE TITLE
getting invalid signature: 0x60809 when try to read

### ISSUE THREAD

**Issue by AhmadZuhdi** [DaSpawn/xlsx-stream-reader#26]
i try to read a file that i got from my friend ([the file](https://drive.google.com/open?id=1QjvhprvuCY42eVkEqqi5qMtIWeTICo0o))

but i got error invalid signature: 0x60809 when try to read

when i try open it with microsoft excel, it was protected, it this the cause of the error ?
this is my code :
```js
import * as XlStream from 'xlsx-stream-reader';
import * as fs from 'fs';

const workBookReader = new XlStream();

const csvData = [];
let columnName = [];

workBookReader.on("error", console.error);

workBookReader.on('worksheet', function (workSheetReader) {
	if (workSheetReader.id > 1){
		// we only want first sheet
		workSheetReader.skip();
		return;
	}

	// print worksheet name
	console.log(workSheetReader.name);

	workSheetReader.on("row", row => {
		if (row.attributes.r == 1){

			row.values.forEach(function(rowVal, colNum){
				columnName.push(rowVal);
			});

			// do something with row 1 like save as column names
		}else{
			// second param to forEach colNum is very important as
			// null columns are not defined in the array, ie sparse array
			let data = {};
			row.values.forEach(function(rowVal, colNum){

				if (rowVal.toString().match(/[0-9.]+/)) {
					data[columnName[colNum-1]] = +parseFloat(rowVal);
				} else {
					data[columnName[colNum-1]] = rowVal;
				}

			});

			csvData.push(data);
		}


	});

	workSheetReader.on('end', function () {
		console.log(workSheetReader.rowCount);
	});

	// call process after registering handlers
	workSheetReader.process();

});

workBookReader.on('end', function () {
	console.log(csvData);
});

fs.createReadStream(`${__dirname}/09082018.xls`).pipe(workBookReader);
```

and this is the full error:
```
Error: invalid signature: 0x60809
    at /Users/ahmadzuhdi/Documents/sites/payroll-backend/node_modules/unzipper/lib/parse.js:57:26
    at tryCatcher (/Users/ahmadzuhdi/Documents/sites/payroll-backend/node_modules/unzipper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ahmadzuhdi/Documents/sites/payroll-backend/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/ahmadzuhdi/Documents/sites/payroll-backend/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/ahmadzuhdi/Documents/sites/payroll-backend/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/ahmadzuhdi/Documents/sites/payroll-backend/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/ahmadzuhdi/Documents/sites/payroll-backend/node_modules/unzipper/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/ahmadzuhdi/Documents/sites/payroll-backend/node_modules/unzipper/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ahmadzuhdi/Documents/sites/payroll-backend/node_modules/unzipper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

```

**Comment by DaSpawn** [comment]
This module is only compatible with newer XLSX files (which are essentially zip files), not the old XLS files
